# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180307_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_course', to='student.Course'),
        ),
    ]
